language: python
python:
  - 3.4
  - 3.5
branches:
  only:
    - master
    - develop
    - /^rel-v(\d+.){0,2}\d+$/
install:
  - pip install flake8
  - pip install coveralls
before_script:
  - "flake8 ."
script:
  - nosetests
  - coverage run --source=cactusbot run.py test
after_success:
  - coveralls
