language: python
python:
  - 3.5
branches:
  only:
    - master
    - develop
    - //^rel-v.+$//
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 run.py config.template.py cactusbot/
